services:
  postgres:
    container_name: hubsesc-db
    image: postgis/postgis:16-3.5
    environment:
      POSTGRES_DB: hubsesc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    ports: ["5432:5432"]
    volumes:
      - ./docker-volumes/database:/var/lib/postgresql/data


  geoserver:
    container_name: hubsesc-geoserver
    build:
      context: .
      dockerfile: ./docker/geoserver/Dockerfile
    depends_on: [postgres]
    ports: ["8080:8080", "2222:2222"]
    environment:
      CORS_ENABLED: "true"
      CORS_ALLOWED_ORIGINS: "*"
      CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,HEAD,OPTIONS"
      CORS_ALLOWED_HEADERS: "*"
    volumes:
      - ./docker-volumes/geoserver:/opt/geoserver_data
